# tanaryo-cloud/docker-compose.yml
version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./services/auth-service:/var/www/auth-service
    working_dir: /var/www/auth-service
    networks:
      - tanaryo-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=auth_service
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - JWT_SECRET=${JWT_SECRET}

  lottery-service:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./services/lottery-service:/var/www/lottery-service
    working_dir: /var/www/lottery-service
    networks:
      - tanaryo-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=lottery_service
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - JWT_SECRET=${JWT_SECRET}

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"  # auth-service
      - "8001:81"  # lottery-service
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./services/auth-service/public:/var/www/auth-service/public
      - ./services/lottery-service/public:/var/www/lottery-service/public
    networks:
      - tanaryo-network
    depends_on:
      - auth-service
      - lottery-service

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=auth_service
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - tanaryo-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

networks:
  tanaryo-network:
    driver: bridge
